### ISSUE TITLE
请问支持readme图片中的中文字体有支持吗？在线网站中没有看到

### ISSUE THREAD

**Issue by fightingst** [korbinzhao/excalidraw-cn#4]

**Comment by fightingst** [comment]
![Uploading screenshot-20230629-160232.png…]()

**Comment by korbinzhao** [comment]
Readme 中的图片是在 MacOS 系统下的导出图片，这个字体是 MacOS 自带中文手写字体，Windows 上不支持。Windows 的中文手写字体是另外一个。所以两个系统的中文手写效果不一样。

你那边是 Windows 系统？感觉 Windows 下中文手写字体不太满意？

MacOS 效果：
![image](https://github.com/korbinzhao/excalidraw-cn/assets/5051627/f81effd1-0445-4d07-a796-e4bfa6592ca8)

Windows 效果：
![image](https://github.com/korbinzhao/excalidraw-cn/assets/5051627/4b8681c1-90a1-44b8-9771-de0c6a48e739)

**Comment by fightingst** [comment]
我是macos  https://handraw.top/  在线使用，显示的是window的效果字体。  这个字体有些字难以辨认，写博客不太适合

**Comment by korbinzhao** [comment]
字体是一个众口难调的事情，近期打算支持下字体自定义，这样你这个问题就可以解决了哈
