### ISSUE TITLE
没有手写效果，只是从宋体成了楷书

### ISSUE THREAD

**Issue by chinfeng** [korbinzhao/excalidraw-cn#6]
![image](https://github.com/korbinzhao/excalidraw-cn/assets/7575491/b8219222-8897-4cfb-ae48-79c64a07c536)

**Comment by korbinzhao** [comment]
咱们这边是 windows 系统还是 macos 系统？直接访问的 handraw.top? 我来具体定位下问题

**Comment by chinfeng** [comment]
win11，我直接访问  handraw.top 也一样的问题，只是成了楷书，没有手写效果

**Comment by korbinzhao** [comment]
可能是中文字体加载失败了，我这边没能复现。先给中文字体增加了 preload，多刷新下试下？中文字体略大第一次加载可能会慢点。
