### ISSUE TITLE
这几个字特别碍眼

### ISSUE THREAD

**Issue by chinfeng** [korbinzhao/excalidraw-cn#7]
好像官方的应用里面也没这几个字，而且这里加载文件也不显示标题，所以这个没用的部分能否去掉？

![image](https://github.com/korbinzhao/excalidraw-cn/assets/7575491/a07f95fc-81d6-4657-b88e-2087d4a6fd88)

**Comment by korbinzhao** [comment]
这几个字是为了在多画布场景下给用户提示区分当前画布的哈，默认文案我优化下。另外，加载文件同步显示文件标题是个很好的优化点，我最近也加下哈。

![image](https://github.com/korbinzhao/excalidraw-cn/assets/5051627/6870381f-23b9-45b2-a371-ae6353163f88)

**Comment by chinfeng** [comment]
我觉得只有一个画布的情况下，这个就不必显示了。

**Comment by korbinzhao** [comment]
只有一个画布的情况下，不显示画布名称，这个建议可以，我支持下。上面说的那个 bug，我试了下，没能复现，不知道是不是理解有偏差，后面我继续关注下看会不会复现。

**Comment by korbinzhao** [comment]
上述反馈问题已解决，具体如下：

Features：
* [x] 只有一个画布的情况下，不显示画布名称。
* [x] 默认画布名称改为 "Default Canvas"。

以上 features 已上线，可访问 [handraw.top](handraw.top) 地址查看。

**Comment by chinfeng** [comment]
给力！赞一个！
